kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kafka-operator
  namespace: ops-middleware
subjects:
- kind: ServiceAccount
  name: kafka-operator
  namespace: ops-middleware
roleRef:
  kind: Role
  name: kafka-operator
  apiGroup: rbac.authorization.k8s.io
